name: medapp4
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  agora_rtc_engine: ^6.2.1
  auto_route: ^7.6.0
  bubble: ^1.2.1
  cached_network_image: ^3.2.3
  chewie: ^1.6.0+1
  cloud_firestore: ^4.8.2
  dio: ^5.2.1+1
  easy_localization: ^3.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.3.3
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.2.4
  flutter_chat_types: ^3.6.1
  flutter_chat_ui: ^1.6.8
  flutter_hooks: ^0.18.6
  flutter_image_compress: ^2.0.3
  flutter_local_notifications: ^15.0.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  icons_plus: ^4.0.0
  image: ^4.0.17
  image_cropper: ^4.0.1
  image_picker: ^1.0.0
  intl: ^0.18.1
  introduction_screen: ^3.1.9
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  lottie: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  photo_view: ^0.14.0
  record: ^4.4.4
  riverpod: ^2.3.6
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.1.2

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/l10n/
    - assets/lottie/
